DROP TABLE IF EXISTS SESSION;
DROP TABLE IF EXISTS REPAIR;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS RENTAL;

CREATE TABLE IF NOT EXISTS ITEM (
    ItemID TEXT NOT NULL PRIMARY KEY,
    Model TEXT NOT NULL,
    PowerOutput DECIMAL(2,1) NOT NULL,
    SignedOut BOOLEAN DEFAULT FALSE,
    Working BOOLEAN DEFAULT TRUE,
    Registered DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS REPAIR (
    RepairID INTEGER NOT NULL CONSTRAINT RepairPK PRIMARY KEY AUTOINCREMENT,
    ItemID TEXT NOT NULL CONSTRAINT RepairFK REFERENCES ITEM,
    State TEXT NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    Requester TEXT DEFAULT 'Anonymous',
    Comments TEXT DEFAULT 'None'
);

CREATE TABLE IF NOT EXISTS SESSION (
    SessionID INTEGER NOT NULL CONSTRAINT SessionPK PRIMARY KEY AUTOINCREMENT,
    ItemID TEXT NOT NULL CONSTRAINT SessionFK REFERENCES ITEM,
    State TEXT NOT NULL,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS RENTAL (
    RentalID INTEGER NOT NULL CONSTRAINT RentalPK PRIMARY KEY AUTOINCREMENT,
    SessionID INTEGER NOT NULL CONSTRAINT RentalFK REFERENCES SESSION,
    Name TEXT,
    PhoneNo TEXT(10)
);
